### ISSUE TITLE
Version 1.3.5 has some weird behaviour

### ISSUE THREAD

**Issue by keithmacklin** [G00fY2/version-compare#9] opened 2020-10-12 21:46 UTC
Hi There - Using the 1.3.5 sample app (and also the 1.3.5 library) I am seeing these issues

1.1.1 should be higher than 1.0.2
![image](https://user-images.githubusercontent.com/20912453/95793031-ae205a80-0cb2-11eb-8183-8a32f080fad4.png)

1.1.1 should be higher than 0.2.2
![image](https://user-images.githubusercontent.com/20912453/95793064-c3958480-0cb2-11eb-9160-62c4f2dedf2e.png)

**Comment by G00fY2** [comment] 2020-10-12 23:42
Hi, thanks for reporting!
I just released an hotfix release 1.3.6 to fix this issue.

I had to remove trailing zeros in the Version object to be able to calculate the same hashcode for 1.0.0 vs 1.0. I didn't pay attention to that part. :dizzy_face: The issue is fixed and I added more test parameters.

Fixed with c8ece3c

**Closed as completed by G00fY2** 2020-10-12 23:42 UTC
